/*
//
//               INTEL CORPORATION PROPRIETARY INFORMATION
//  This software is supplied under the terms of a license agreement or
//  nondisclosure agreement with Intel Corporation and may not be copied
//  or disclosed except in accordance with the terms of that agreement.
//        Copyright(c) 1999-2012 Intel Corporation. All Rights Reserved.
//
*/

// Run2.cpp : implementation of the CRun2 class.
// CRun2 class processes vectors by ippSP functions listed in
// CallIppFunction member function.
// See CRun & CippsRun classes for more information.
//
/////////////////////////////////////////////////////////////////////////////

#include "stdafx.h"
#include "ippsDemo.h"
#include "Run2.h"
#include "Parm2Dlg.h"

#ifdef _DEBUG
#undef THIS_FILE
static char THIS_FILE[]=__FILE__;
#define new DEBUG_NEW
#endif

//////////////////////////////////////////////////////////////////////
// Construction/Destruction
//////////////////////////////////////////////////////////////////////

CParamDlg* CRun2::CreateDlg() { 
   return new CParm2Dlg;
}

BOOL CRun2::Open(CFunc func)
{
   if (!CippsRun::Open(func)) return FALSE;
   if (func.BaseName() == "CplxToReal" ||
       func.BaseName() == "CartToPolar")
      m_UsedVectors = VEC_SRC|VEC_DST|VEC_DST2;
   if (func.BaseName() == "Zero")
      m_UsedVectors = VEC_SRC;
   return TRUE;
}

IppStatus CRun2::CallIppFunction()
{
   FUNC_CALL(ippsCartToPolar_32fc,((Ipp32fc*)pSrc, (Ipp32f*)pDst,
                                               (Ipp32f*)pDst2, len))
   FUNC_CALL(ippsCartToPolar_64fc,((Ipp64fc*)pSrc, (Ipp64f*)pDst,
                                                   (Ipp64f*)pDst2, len))
   FUNC_CALL(ippsZero_8u,((Ipp8u*)pSrc, len ))
   FUNC_CALL(ippsZero_16s,((Ipp16s*)pSrc, len ))
   FUNC_CALL(ippsZero_16sc,((Ipp16sc*)pSrc, len ))
   FUNC_CALL(ippsZero_32s,((Ipp32s*)pSrc, len ))
   FUNC_CALL(ippsZero_32sc,((Ipp32sc*)pSrc, len ))
   FUNC_CALL(ippsZero_64s,((Ipp64s*)pSrc, len ))
   FUNC_CALL(ippsZero_64sc,((Ipp64sc*)pSrc, len ))
   FUNC_CALL(ippsZero_32f,((Ipp32f*)pSrc, len ))
   FUNC_CALL(ippsZero_32fc,((Ipp32fc*)pSrc, len ))
   FUNC_CALL(ippsZero_64f,((Ipp64f*)pSrc, len ))
   FUNC_CALL(ippsZero_64fc,((Ipp64fc*)pSrc, len ))
   FUNC_CALL(ippsMagnitude_32fc,   ((Ipp32fc*)pSrc,(Ipp32f*)pDst,len))
   FUNC_CALL(ippsMagnitude_64fc,   ((Ipp64fc*)pSrc,(Ipp64f*)pDst,len))
   FUNC_CALL(ippsMagnitude_16sc32f,((Ipp16sc*)pSrc,(Ipp32f*)pDst,len))
   FUNC_CALL(ippsMagnitude_16sc_Sfs,((Ipp16sc*)pSrc,(Ipp16s*)pDst,len,scaleFactor))
   FUNC_CALL(ippsMagnitude_32sc_Sfs,((Ipp32sc*)pSrc,(Ipp32s*)pDst,len,scaleFactor))
   FUNC_CALL(ippsMagSquared_32sc32s_Sfs,((Ipp32sc*)pSrc,(Ipp32s*)pDst, len, scaleFactor))
   FUNC_CALL(ippsPhase_64fc,((Ipp64fc*)pSrc, (Ipp64f*)pDst, len))
   FUNC_CALL(ippsPhase_32fc,((Ipp32fc*)pSrc, (Ipp32f*)pDst, len))
   FUNC_CALL(ippsPhase_16sc32f,((Ipp16sc*)pSrc, (Ipp32f*)pDst, len))
   FUNC_CALL(ippsPhase_16sc_Sfs,((Ipp16sc*)pSrc, (Ipp16s*)pDst, len, scaleFactor))
   FUNC_CALL(ippsPhase_32sc_Sfs,((Ipp32sc*)pSrc, (Ipp32s*)pDst, len, scaleFactor))
   FUNC_CALL(ippsReal_64fc, ((Ipp64fc*)pSrc, (Ipp64f*)pDst, len))
   FUNC_CALL(ippsReal_32fc, ((Ipp32fc*)pSrc, (Ipp32f*)pDst, len))
   FUNC_CALL(ippsReal_16sc, ((Ipp16sc*)pSrc, (Ipp16s*)pDst, len))
   FUNC_CALL(ippsImag_64fc, ((Ipp64fc*)pSrc, (Ipp64f*)pDst, len))
   FUNC_CALL(ippsImag_32fc, ((Ipp32fc*)pSrc, (Ipp32f*)pDst, len))
   FUNC_CALL(ippsImag_16sc, ((Ipp16sc*)pSrc, (Ipp16s*)pDst, len))
   FUNC_CALL(ippsCplxToReal_64fc,
       ((Ipp64fc*)pSrc,(Ipp64f*)pDst,(Ipp64f*)pDst2, len ))
   FUNC_CALL(ippsCplxToReal_32fc,
       ((Ipp32fc*)pSrc,(Ipp32f*)pDst,(Ipp32f*)pDst2, len ))
   FUNC_CALL(ippsCplxToReal_16sc,
       ((Ipp16sc*)pSrc,(Ipp16s*)pDst,(Ipp16s*)pDst2, len ))
   FUNC_CALL(ippsConj_64fc_I, ( (Ipp64fc*)pSrc, len )) 
   FUNC_CALL(ippsConj_32fc_I, ( (Ipp32fc*)pSrc, len )) 
   FUNC_CALL(ippsConj_16sc_I, ( (Ipp16sc*)pSrc, len )) 
   FUNC_CALL(ippsConj_64fc, ( (Ipp64fc*)pSrc, (Ipp64fc*)pDst, len )) 
   FUNC_CALL(ippsConj_32fc, ( (Ipp32fc*)pSrc, (Ipp32fc*)pDst, len )) 
   FUNC_CALL(ippsConj_16sc, ( (Ipp16sc*)pSrc, (Ipp16sc*)pDst, len )) 
   FUNC_CALL(ippsConjFlip_64fc, ( (Ipp64fc*)pSrc, (Ipp64fc*)pDst, len )) 
   FUNC_CALL(ippsConjFlip_32fc, ( (Ipp32fc*)pSrc, (Ipp32fc*)pDst, len )) 
   FUNC_CALL(ippsConjFlip_16sc, ( (Ipp16sc*)pSrc, (Ipp16sc*)pDst, len )) 
   FUNC_CALL(ippsCopy_8u, ( (Ipp8u*)pSrc, (Ipp8u*)pDst, len ))
   FUNC_CALL(ippsCopy_16s, ( (Ipp16s*)pSrc, (Ipp16s*)pDst, len ))
   FUNC_CALL(ippsCopy_16sc, ( (Ipp16sc*)pSrc, (Ipp16sc*)pDst, len ))
   FUNC_CALL(ippsCopy_32f, ( (Ipp32f*)pSrc, (Ipp32f*)pDst, len ))
   FUNC_CALL(ippsCopy_32fc, ( (Ipp32fc*)pSrc, (Ipp32fc*)pDst, len ))
   FUNC_CALL(ippsCopy_64f, ( (Ipp64f*)pSrc, (Ipp64f*)pDst, len ))
   FUNC_CALL(ippsCopy_64fc, ( (Ipp64fc*)pSrc, (Ipp64fc*)pDst, len ))
   FUNC_CALL(ippsCopy_32s, ( (Ipp32s*)pSrc, (Ipp32s*)pDst, len ))
   FUNC_CALL(ippsCopy_32sc, ( (Ipp32sc*)pSrc, (Ipp32sc*)pDst, len ))
   FUNC_CALL(ippsCopy_64s, ( (Ipp64s*)pSrc, (Ipp64s*)pDst, len ))
   FUNC_CALL(ippsCopy_64sc, ( (Ipp64sc*)pSrc, (Ipp64sc*)pDst, len ))
   FUNC_CALL(ippsConvert_8s16s,((Ipp8s*)pSrc,(Ipp16s*)pDst, len))
   FUNC_CALL(ippsConvert_8s32f,((Ipp8s*)pSrc,(Ipp32f*)pDst,len))
   FUNC_CALL(ippsConvert_8u32f,((Ipp8u*)pSrc,(Ipp32f*)pDst,len))
   FUNC_CALL(ippsConvert_16s32f,((Ipp16s*)pSrc,(Ipp32f*)pDst,len))
   FUNC_CALL(ippsConvert_16u32f,((Ipp16u*)pSrc,(Ipp32f*)pDst,len))
   FUNC_CALL(ippsConvert_32s64f,((Ipp32s*)pSrc,(Ipp64f*)pDst,len))
   FUNC_CALL(ippsConvert_32s32f,((Ipp32s*)pSrc,(Ipp32f*)pDst,len))
   FUNC_CALL(ippsConvert_32f64f,((Ipp32f*)pSrc,(Ipp64f*)pDst,len))
   FUNC_CALL(ippsConvert_64f32f,((Ipp64f*)pSrc,(Ipp32f*)pDst,len)) 
   FUNC_CALL(ippsConvert_16s32s,((Ipp16s*)pSrc,(Ipp32s*)pDst,len))
   FUNC_CALL(ippsConvert_32s16s,((Ipp32s*)pSrc,(Ipp16s*)pDst,len))
   FUNC_CALL(ippsConvert_32s16s_Sfs,((Ipp32s*)pSrc,(Ipp16s*)pDst,len, scaleFactor))
   FUNC_CALL(ippsConvert_16s32f_Sfs, ((Ipp16s*)pSrc, (Ipp32f*)pDst, len, scaleFactor ))
   FUNC_CALL(ippsConvert_16s64f_Sfs, ((Ipp16s*)pSrc, (Ipp64f*)pDst, len, scaleFactor ))
   FUNC_CALL(ippsConvert_32s32f_Sfs, ((Ipp32s*)pSrc, (Ipp32f*)pDst, len, scaleFactor ))
   FUNC_CALL(ippsConvert_32s64f_Sfs, ((Ipp32s*)pSrc, (Ipp64f*)pDst, len, scaleFactor ))
   FUNC_CALL(ippsConvert_24u32u, ((Ipp8u*)pSrc, (Ipp32u*)pDst, len ))
   FUNC_CALL(ippsConvert_32u24u_Sfs, ((Ipp32u*)pSrc, (Ipp8u*)pDst, len, scaleFactor )) 
   FUNC_CALL(ippsConvert_24u32f, ((Ipp8u*)pSrc, (Ipp32f*)pDst, len ))
   FUNC_CALL(ippsConvert_32f24u_Sfs, ((Ipp32f*)pSrc, (Ipp8u*)pDst, len, scaleFactor ))
   FUNC_CALL(ippsConvert_24s32s, ((Ipp8u*)pSrc, (Ipp32s*)pDst, len ))
   FUNC_CALL(ippsConvert_32s24s_Sfs, ((Ipp32s*)pSrc, (Ipp8u*)pDst, len, scaleFactor )) 
   FUNC_CALL(ippsConvert_24s32f, ((Ipp8u*)pSrc, (Ipp32f*)pDst, len ))
   FUNC_CALL(ippsConvert_32f24s_Sfs, ((Ipp32f*)pSrc, (Ipp8u*)pDst, len, scaleFactor ))
   FUNC_CALL(ippsConvert_16f32f,((Ipp16f*)pSrc,(Ipp32f*)pDst,len))
   FUNC_CALL(ippsConj_64fc_I, ((Ipp64fc*)pSrc, len )) 
   FUNC_CALL(ippsConj_32fc_I, ((Ipp32fc*)pSrc, len )) 
   FUNC_CALL(ippsConj_16sc_I, ((Ipp16sc*)pSrc, len )) 
   FUNC_CALL(ippsConj_64fc,      ((Ipp64fc*)pSrc, (Ipp64fc*)pDst, len )) 
   FUNC_CALL(ippsConj_32fc,      ((Ipp32fc*)pSrc, (Ipp32fc*)pDst, len )) 
   FUNC_CALL(ippsConj_16sc,      ((Ipp16sc*)pSrc, (Ipp16sc*)pDst, len )) 
   FUNC_CALL(ippsConjFlip_64fc,  ((Ipp64fc*)pSrc, (Ipp64fc*)pDst, len )) 
   FUNC_CALL(ippsConjFlip_32fc,  ((Ipp32fc*)pSrc, (Ipp32fc*)pDst, len )) 
   FUNC_CALL(ippsConjFlip_16sc,  ((Ipp16sc*)pSrc, (Ipp16sc*)pDst, len )) 
   FUNC_CALL(ippsConjCcs_64fc_I, ((Ipp64fc*)pSrc, len )) 
   FUNC_CALL(ippsConjCcs_32fc_I, ((Ipp32fc*)pSrc, len )) 
   FUNC_CALL(ippsConjCcs_16sc_I, ((Ipp16sc*)pSrc, len )) 
   FUNC_CALL(ippsConjCcs_64fc,   ((Ipp64f*)pSrc, (Ipp64fc*)pDst, len )) 
   FUNC_CALL(ippsConjCcs_32fc,   ((Ipp32f*)pSrc, (Ipp32fc*)pDst, len )) 
   FUNC_CALL(ippsConjCcs_16sc,   ((Ipp16s*)pSrc, (Ipp16sc*)pDst, len )) 
   FUNC_CALL(ippsConjPack_64fc_I,((Ipp64fc*)pSrc, len )) 
   FUNC_CALL(ippsConjPack_32fc_I,((Ipp32fc*)pSrc, len )) 
   FUNC_CALL(ippsConjPack_16sc_I,((Ipp16sc*)pSrc, len )) 
   FUNC_CALL(ippsConjPack_64fc,  ((Ipp64f*)pSrc, (Ipp64fc*)pDst, len )) 
   FUNC_CALL(ippsConjPack_32fc,  ((Ipp32f*)pSrc, (Ipp32fc*)pDst, len )) 
   FUNC_CALL(ippsConjPack_16sc,  ((Ipp16s*)pSrc, (Ipp16sc*)pDst, len )) 
   FUNC_CALL(ippsConjPerm_64fc_I,((Ipp64fc*)pSrc, len )) 
   FUNC_CALL(ippsConjPerm_32fc_I,((Ipp32fc*)pSrc, len )) 
   FUNC_CALL(ippsConjPerm_16sc_I,((Ipp16sc*)pSrc, len )) 
   FUNC_CALL(ippsConjPerm_64fc,  ((Ipp64f*)pSrc, (Ipp64fc*)pDst, len )) 
   FUNC_CALL(ippsConjPerm_32fc,  ((Ipp32f*)pSrc, (Ipp32fc*)pDst, len )) 
   FUNC_CALL(ippsConjPerm_16sc,  ((Ipp16s*)pSrc, (Ipp16sc*)pDst, len )) 
   FUNC_CALL(ippsExp_32f_I,((Ipp32f*)pSrc, len))
   FUNC_CALL(ippsExp_64f_I,((Ipp64f*)pSrc, len))
   FUNC_CALL(ippsExp_16s_ISfs,((Ipp16s*)pSrc, len, scaleFactor))
   FUNC_CALL(ippsExp_32s_ISfs,((Ipp32s*)pSrc, len, scaleFactor))
   FUNC_CALL(ippsExp_64s_ISfs,((Ipp64s*)pSrc, len, scaleFactor))
   FUNC_CALL(ippsExp_32f, ((Ipp32f*)pSrc, (Ipp32f*)pDst, len))
   FUNC_CALL(ippsExp_64f, ((Ipp64f*)pSrc, (Ipp64f*)pDst, len))
   FUNC_CALL(ippsExp_16s_Sfs,((Ipp16s*)pSrc, (Ipp16s*)pDst, len, scaleFactor))
   FUNC_CALL(ippsExp_32s_Sfs,((Ipp32s*)pSrc, (Ipp32s*)pDst, len, scaleFactor))
   FUNC_CALL(ippsExp_64s_Sfs,((Ipp64s*)pSrc, (Ipp64s*)pDst, len, scaleFactor))
   FUNC_CALL(ippsExp_32f64f,((Ipp32f*)pSrc, (Ipp64f*)pDst, len))
   FUNC_CALL(ippsLn_32f_I,((Ipp32f*)pSrc, len))
   FUNC_CALL(ippsLn_64f_I,((Ipp64f*)pSrc, len))
   FUNC_CALL(ippsLn_32f, ((Ipp32f*)pSrc, (Ipp32f*)pDst, len))
   FUNC_CALL(ippsLn_64f, ((Ipp64f*)pSrc, (Ipp64f*)pDst, len))
   FUNC_CALL(ippsLn_64f32f,((Ipp64f*)pSrc, (Ipp32f*)pDst, len))
   FUNC_CALL(ippsLn_16s_ISfs,((Ipp16s*)pSrc, len, scaleFactor))
   FUNC_CALL(ippsLn_16s_Sfs,((Ipp16s*)pSrc, (Ipp16s*)pDst, len, scaleFactor))
   FUNC_CALL(ippsLn_32s_ISfs,((Ipp32s*)pSrc, len, scaleFactor))
   FUNC_CALL(ippsLn_32s_Sfs,((Ipp32s*)pSrc, (Ipp32s*)pDst, len, scaleFactor))
   FUNC_CALL(ippsLn_32s16s_Sfs,((Ipp32s*)pSrc, (Ipp16s*)pDst, len, scaleFactor))
   FUNC_CALL(ipps10Log10_32s_ISfs,( (Ipp32s*)pSrc, len, scaleFactor))
   FUNC_CALL(ipps10Log10_32s_Sfs, ( (Ipp32s*)pSrc, (Ipp32s*)pDst, len, scaleFactor))
   FUNC_CALL(ippsSqr_32f_I,((Ipp32f*)pSrc, len))
   FUNC_CALL(ippsSqr_32fc_I,((Ipp32fc*)pSrc, len))
   FUNC_CALL(ippsSqr_64f_I,((Ipp64f*)pSrc, len))
   FUNC_CALL(ippsSqr_64fc_I,((Ipp64fc*)pSrc, len))
   FUNC_CALL(ippsSqr_32f,((Ipp32f*)pSrc, (Ipp32f*)pDst, len))
   FUNC_CALL(ippsSqr_32fc,((Ipp32fc*)pSrc, (Ipp32fc*)pDst, len))
   FUNC_CALL(ippsSqr_64f,((Ipp64f*)pSrc, (Ipp64f*)pDst, len))
   FUNC_CALL(ippsSqr_64fc,((Ipp64fc*)pSrc, (Ipp64fc*)pDst, len))
   FUNC_CALL(ippsSqr_16s_ISfs,((Ipp16s*)pSrc, len, scaleFactor))
   FUNC_CALL(ippsSqr_16sc_ISfs,((Ipp16sc*)pSrc, len, scaleFactor))
   FUNC_CALL(ippsSqr_16s_Sfs,((Ipp16s*)pSrc, (Ipp16s*)pDst, len, scaleFactor))
   FUNC_CALL(ippsSqr_16sc_Sfs,((Ipp16sc*)pSrc, (Ipp16sc*)pDst, len, scaleFactor))
   FUNC_CALL(ippsSqr_8u_ISfs,((Ipp8u*)pSrc, len, scaleFactor))
   FUNC_CALL(ippsSqr_8u_Sfs,((Ipp8u*)pSrc, (Ipp8u*)pDst, len, scaleFactor))
   FUNC_CALL(ippsSqr_16u_ISfs,((Ipp16u*)pSrc, len, scaleFactor))
   FUNC_CALL(ippsSqr_16u_Sfs,((Ipp16u*)pSrc, (Ipp16u*)pDst, len, scaleFactor))
   FUNC_CALL(ippsSqrt_32f_I,((Ipp32f*)pSrc,len))
   FUNC_CALL(ippsSqrt_32fc_I,((Ipp32fc*)pSrc,len))
   FUNC_CALL(ippsSqrt_64f_I,((Ipp64f*)pSrc,len))
   FUNC_CALL(ippsSqrt_64fc_I,((Ipp64fc*)pSrc,len))
   FUNC_CALL(ippsSqrt_32f,((Ipp32f*)pSrc,(Ipp32f*)pDst,len))
   FUNC_CALL(ippsSqrt_32fc,((Ipp32fc*)pSrc,(Ipp32fc*)pDst,len))
   FUNC_CALL(ippsSqrt_64f,((Ipp64f*)pSrc,(Ipp64f*)pDst,len))
   FUNC_CALL(ippsSqrt_64fc,((Ipp64fc*)pSrc,(Ipp64fc*)pDst,len))
   FUNC_CALL(ippsSqrt_8u_ISfs,((Ipp8u*)pSrc,len,scaleFactor))
   FUNC_CALL(ippsSqrt_8u_Sfs,((Ipp8u*)pSrc,(Ipp8u*)pDst,len,scaleFactor))
   FUNC_CALL(ippsSqrt_16u_ISfs,((Ipp16u*)pSrc,len,scaleFactor))
   FUNC_CALL(ippsSqrt_16u_Sfs,((Ipp16u*)pSrc,(Ipp16u*)pDst,len,scaleFactor))
   FUNC_CALL(ippsSqrt_16s_ISfs,((Ipp16s*)pSrc,len,scaleFactor))
   FUNC_CALL(ippsSqrt_16sc_ISfs,((Ipp16sc*)pSrc,len,scaleFactor))
   FUNC_CALL(ippsSqrt_16s_Sfs,((Ipp16s*)pSrc,(Ipp16s*)pDst,len,scaleFactor))
   FUNC_CALL(ippsSqrt_16sc_Sfs,((Ipp16sc*)pSrc,(Ipp16sc*)pDst,len,scaleFactor))
   FUNC_CALL(ippsSqrt_64s_ISfs,((Ipp64s*)pSrc,len,scaleFactor))
   FUNC_CALL(ippsSqrt_64s_Sfs,((Ipp64s*)pSrc,(Ipp64s*)pDst,len,scaleFactor))
   FUNC_CALL(ippsSqrt_32s16s_Sfs,((Ipp32s*)pSrc,(Ipp16s*)pDst,len,scaleFactor))
   FUNC_CALL(ippsSqrt_64s16s_Sfs,((Ipp64s*)pSrc,(Ipp16s*)pDst,len,scaleFactor))
   FUNC_CALL(ippsCubrt_32s16s_Sfs,((Ipp32s*)pSrc,(Ipp16s*)pDst,len,scaleFactor))
   FUNC_CALL(ippsCubrt_32f,       ((Ipp32f*)pSrc,(Ipp32f*)pDst,len))
   FUNC_CALL(ippsAbs_32f_I,((Ipp32f*)pSrc,len))
   FUNC_CALL(ippsAbs_64f_I,((Ipp64f*)pSrc,len))
   FUNC_CALL(ippsAbs_16s_I,((Ipp16s*)pSrc,len))
   FUNC_CALL(ippsAbs_32s_I,((Ipp32s*)pSrc,len))
   FUNC_CALL(ippsAbs_32f,((Ipp32f*)pSrc, (Ipp32f*)pDst,len))
   FUNC_CALL(ippsAbs_64f,((Ipp64f*)pSrc, (Ipp64f*)pDst,len))
   FUNC_CALL(ippsAbs_16s,((Ipp16s*)pSrc, (Ipp16s*)pDst,len))
   FUNC_CALL(ippsAbs_32s,((Ipp32s*)pSrc, (Ipp32s*)pDst,len))
   FUNC_CALL(ippsWinBartlett_16s_I, ((Ipp16s*)pSrc, len))
   FUNC_CALL(ippsWinBartlett_16sc_I, ((Ipp16sc*)pSrc, len))
   FUNC_CALL(ippsWinBartlett_32f_I, ((Ipp32f*)pSrc, len))
   FUNC_CALL(ippsWinBartlett_32fc_I, ((Ipp32fc*)pSrc, len))
   FUNC_CALL(ippsWinBartlett_64f_I, ((Ipp64f*)pSrc, len))
   FUNC_CALL(ippsWinBartlett_64fc_I, ((Ipp64fc*)pSrc, len))
   FUNC_CALL(ippsWinBartlett_16s, ((Ipp16s*)pSrc, (Ipp16s*)pDst, len))
   FUNC_CALL(ippsWinBartlett_16sc, ((Ipp16sc*)pSrc, (Ipp16sc*)pDst, len))
   FUNC_CALL(ippsWinBartlett_32f, ((Ipp32f*)pSrc, (Ipp32f*)pDst, len))
   FUNC_CALL(ippsWinBartlett_32fc, ((Ipp32fc*)pSrc, (Ipp32fc*)pDst, len))
   FUNC_CALL(ippsWinBartlett_64f, ((Ipp64f*)pSrc, (Ipp64f*)pDst, len))
   FUNC_CALL(ippsWinBartlett_64fc, ((Ipp64fc*)pSrc, (Ipp64fc*)pDst, len))
   FUNC_CALL(ippsWinHann_16s_I, ((Ipp16s*)pSrc, len))
   FUNC_CALL(ippsWinHann_16sc_I, ((Ipp16sc*)pSrc, len))
   FUNC_CALL(ippsWinHann_32f_I, ((Ipp32f*)pSrc, len))
   FUNC_CALL(ippsWinHann_32fc_I, ((Ipp32fc*)pSrc, len))
   FUNC_CALL(ippsWinHann_64f_I, ((Ipp64f*)pSrc, len))
   FUNC_CALL(ippsWinHann_64fc_I, ((Ipp64fc*)pSrc, len))
   FUNC_CALL(ippsWinHann_16s, ((Ipp16s*)pSrc, (Ipp16s*)pDst, len))
   FUNC_CALL(ippsWinHann_16sc, ((Ipp16sc*)pSrc, (Ipp16sc*)pDst, len))
   FUNC_CALL(ippsWinHann_32f, ((Ipp32f*)pSrc, (Ipp32f*)pDst, len))
   FUNC_CALL(ippsWinHann_32fc, ((Ipp32fc*)pSrc, (Ipp32fc*)pDst, len))
   FUNC_CALL(ippsWinHann_64f, ((Ipp64f*)pSrc, (Ipp64f*)pDst, len))
   FUNC_CALL(ippsWinHann_64fc, ((Ipp64fc*)pSrc, (Ipp64fc*)pDst, len))
   FUNC_CALL(ippsWinHamming_16s_I, ((Ipp16s*)pSrc, len))
   FUNC_CALL(ippsWinHamming_16sc_I, ((Ipp16sc*)pSrc, len))
   FUNC_CALL(ippsWinHamming_32f_I, ((Ipp32f*)pSrc, len))
   FUNC_CALL(ippsWinHamming_32fc_I, ((Ipp32fc*)pSrc, len))
   FUNC_CALL(ippsWinHamming_64f_I, ((Ipp64f*)pSrc, len))
   FUNC_CALL(ippsWinHamming_64fc_I, ((Ipp64fc*)pSrc, len))
   FUNC_CALL(ippsWinHamming_16s, ((Ipp16s*)pSrc, (Ipp16s*)pDst, len))
   FUNC_CALL(ippsWinHamming_16sc, ((Ipp16sc*)pSrc, (Ipp16sc*)pDst, len))
   FUNC_CALL(ippsWinHamming_32f, ((Ipp32f*)pSrc, (Ipp32f*)pDst, len))
   FUNC_CALL(ippsWinHamming_32fc, ((Ipp32fc*)pSrc, (Ipp32fc*)pDst, len))
   FUNC_CALL(ippsWinHamming_64f, ((Ipp64f*)pSrc, (Ipp64f*)pDst, len))
   FUNC_CALL(ippsWinHamming_64fc, ((Ipp64fc*)pSrc, (Ipp64fc*)pDst, len))
   FUNC_CALL(ippsWinBlackmanStd_16s_I, ((Ipp16s*)pSrc, len))
   FUNC_CALL(ippsWinBlackmanStd_16sc_I, ((Ipp16sc*)pSrc, len))
   FUNC_CALL(ippsWinBlackmanStd_32f_I, ((Ipp32f*)pSrc, len))
   FUNC_CALL(ippsWinBlackmanStd_32fc_I, ((Ipp32fc*)pSrc, len))
   FUNC_CALL(ippsWinBlackmanStd_64f_I, ((Ipp64f*)pSrc, len))
   FUNC_CALL(ippsWinBlackmanStd_64fc_I, ((Ipp64fc*)pSrc, len))
   FUNC_CALL(ippsWinBlackmanOpt_16s_I, ((Ipp16s*)pSrc, len))
   FUNC_CALL(ippsWinBlackmanOpt_16sc_I, ((Ipp16sc*)pSrc, len))
   FUNC_CALL(ippsWinBlackmanOpt_32f_I, ((Ipp32f*)pSrc, len))
   FUNC_CALL(ippsWinBlackmanOpt_32fc_I, ((Ipp32fc*)pSrc, len))
   FUNC_CALL(ippsWinBlackmanOpt_64f_I, ((Ipp64f*)pSrc, len))
   FUNC_CALL(ippsWinBlackmanOpt_64fc_I, ((Ipp64fc*)pSrc, len))
   FUNC_CALL(ippsWinBlackmanStd_16s, ((Ipp16s*)pSrc, (Ipp16s*)pDst, len))
   FUNC_CALL(ippsWinBlackmanStd_16sc, ((Ipp16sc*)pSrc, (Ipp16sc*)pDst, len))
   FUNC_CALL(ippsWinBlackmanStd_32f, ((Ipp32f*)pSrc, (Ipp32f*)pDst, len))
   FUNC_CALL(ippsWinBlackmanStd_32fc, ((Ipp32fc*)pSrc, (Ipp32fc*)pDst, len))
   FUNC_CALL(ippsWinBlackmanStd_64f, ((Ipp64f*)pSrc, (Ipp64f*)pDst, len))
   FUNC_CALL(ippsWinBlackmanStd_64fc, ((Ipp64fc*)pSrc, (Ipp64fc*)pDst, len))
   FUNC_CALL(ippsWinBlackmanOpt_16s, ((Ipp16s*)pSrc, (Ipp16s*)pDst, len))
   FUNC_CALL(ippsWinBlackmanOpt_16sc, ((Ipp16sc*)pSrc, (Ipp16sc*)pDst, len))
   FUNC_CALL(ippsWinBlackmanOpt_32f, ((Ipp32f*)pSrc, (Ipp32f*)pDst, len))
   FUNC_CALL(ippsWinBlackmanOpt_32fc, ((Ipp32fc*)pSrc, (Ipp32fc*)pDst, len))
   FUNC_CALL(ippsWinBlackmanOpt_64f, ((Ipp64f*)pSrc, (Ipp64f*)pDst, len))
   FUNC_CALL(ippsWinBlackmanOpt_64fc, ((Ipp64fc*)pSrc, (Ipp64fc*)pDst, len))
   FUNC_CALL(ippsPowerSpectr_64fc,( (Ipp64fc*)pSrc, (Ipp64f*)pDst, len))
   FUNC_CALL(ippsPowerSpectr_32fc,( (Ipp32fc*)pSrc, (Ipp32f*)pDst, len))
   FUNC_CALL(ippsPowerSpectr_16sc_Sfs,( (Ipp16sc*)pSrc, (Ipp16s*)pDst,len, scaleFactor))
   FUNC_CALL(ippsPowerSpectr_16sc32f, ( (Ipp16sc*)pSrc, (Ipp32f*)pDst, len))
   FUNC_CALL(ippsNot_8u_I, ((Ipp8u*)pSrc, len))
   FUNC_CALL(ippsNot_8u, ((Ipp8u*)pSrc, (Ipp8u*)pDst, len))
   FUNC_CALL(ippsNot_16u_I, ((Ipp16u*)pSrc, len))
   FUNC_CALL(ippsNot_16u, ((Ipp16u*)pSrc, (Ipp16u*)pDst, len))
   FUNC_CALL(ippsNot_32u_I, ((Ipp32u*)pSrc, len))
   FUNC_CALL(ippsNot_32u, ((Ipp32u*)pSrc, (Ipp32u*)pDst, len))
   FUNC_CALL(ippsALawToLin_8u32f, ((Ipp8u*)pSrc, (Ipp32f*)pDst, len))
   FUNC_CALL(ippsLinToALaw_32f8u, ((Ipp32f*)pSrc, (Ipp8u*)pDst, len))
   FUNC_CALL(ippsALawToLin_8u16s, ((Ipp8u*)pSrc, (Ipp16s*)pDst, len))
   FUNC_CALL(ippsLinToALaw_16s8u, ((Ipp16s*)pSrc, (Ipp8u*)pDst, len))
   FUNC_CALL(ippsMuLawToLin_8u32f, ((Ipp8u*)pSrc, (Ipp32f*)pDst, len))
   FUNC_CALL(ippsLinToMuLaw_32f8u, ((Ipp32f*)pSrc, (Ipp8u*)pDst, len))
   FUNC_CALL(ippsMuLawToLin_8u16s, ((Ipp8u*)pSrc, (Ipp16s*)pDst, len))
   FUNC_CALL(ippsLinToMuLaw_16s8u, ((Ipp16s*)pSrc, (Ipp8u*)pDst, len))
   FUNC_CALL(ippsALawToMuLaw_8u,  ((Ipp8u*)pSrc, (Ipp8u*)pDst, len))
   FUNC_CALL(ippsMuLawToALaw_8u,   ((Ipp8u*)pSrc, (Ipp8u*)pDst, len))
   FUNC_CALL(ippsArctan_32f_I,((Ipp32f*)pSrc, len))
   FUNC_CALL(ippsArctan_32f,  ((Ipp32f*)pSrc, (Ipp32f*)pDst, len))
   FUNC_CALL(ippsArctan_64f_I,((Ipp64f*)pSrc, len))
   FUNC_CALL(ippsArctan_64f,  ((Ipp64f*)pSrc, (Ipp64f*)pDst, len))
   FUNC_CALL(ippsFlip_8u,( (Ipp8u*)pSrc, (Ipp8u*)pDst, len ))
   FUNC_CALL(ippsFlip_8u_I,( (Ipp8u*)pSrc, len ))
   FUNC_CALL(ippsFlip_16u,( (Ipp16u*)pSrc, (Ipp16u*)pDst, len ))
   FUNC_CALL(ippsFlip_16u_I,( (Ipp16u*)pSrc, len ))
   FUNC_CALL(ippsFlip_32f,( (Ipp32f*)pSrc, (Ipp32f*)pDst, len ))
   FUNC_CALL(ippsFlip_32f_I,( (Ipp32f*)pSrc, len ))
   FUNC_CALL(ippsFlip_64f,( (Ipp64f*)pSrc, (Ipp64f*)pDst, len ))
   FUNC_CALL(ippsFlip_64f_I,( (Ipp64f*)pSrc, len ))
   FUNC_CALL(ippsSortAscend_8u_I,   ((Ipp8u*) pSrc, len))
   FUNC_CALL(ippsSortAscend_16s_I,  ((Ipp16s*)pSrc, len))
   FUNC_CALL(ippsSortAscend_32s_I,  ((Ipp32s*)pSrc, len))
   FUNC_CALL(ippsSortAscend_32f_I,  ((Ipp32f*)pSrc, len))
   FUNC_CALL(ippsSortAscend_64f_I,  ((Ipp64f*)pSrc, len))

   FUNC_CALL(ippsSortDescend_8u_I,  ((Ipp8u*) pSrc, len))
   FUNC_CALL(ippsSortDescend_16s_I, ((Ipp16s*)pSrc, len))
   FUNC_CALL(ippsSortDescend_32s_I, ((Ipp32s*)pSrc, len))
   FUNC_CALL(ippsSortDescend_32f_I, ((Ipp32f*)pSrc, len))
   FUNC_CALL(ippsSortDescend_64f_I, ((Ipp64f*)pSrc, len))
   FUNC_CALL(ippsSwapBytes_16u_I, ( (Ipp16u*)pSrc, len ))
   FUNC_CALL(ippsSwapBytes_24u_I, ( (Ipp8u*) pSrc, len ))
   FUNC_CALL(ippsSwapBytes_32u_I, ( (Ipp32u*)pSrc, len ))
   FUNC_CALL(ippsSwapBytes_16u,   ((Ipp16u*)pSrc, (Ipp16u*)pDst, len ))
   FUNC_CALL(ippsSwapBytes_24u,   ((Ipp8u*) pSrc, (Ipp8u*) pDst, len ))
   FUNC_CALL(ippsSwapBytes_32u,   ((Ipp32u*)pSrc, (Ipp32u*)pDst, len ))

   return stsNoFunction;
}
